### ISSUE TITLE
DB permissions are affected by umask

### ISSUE THREAD

**Issue by iainhallam** [jps-help/dconf#7]
When managing a database, the `dconf_update` exec compiles the ini files into the binary form, but unless the umask is 022, the resulting database might not be readable by all users (see, for example, https://gitlab.gnome.org/GNOME/dconf/-/issues/76). On Ubuntu, root's umask seems to be 077, so this causes issues. Can an explicit line be added to the `dconf_update` exec?

```puppet
  exec { 'dconf_update':
    path        => ['/usr/bin','/usr/sbin'],
    command     => 'dconf update',
    refreshonly => true,
    umask       => '022',
  }
```

**Comment by jps-help** [comment]
Good catch. I've tested this myself and can see the module would be affected.

This should be fixed upstream, but it's easy enough to push a workaround for now. I'll look into it.
